# Generated by Django 2.2.1 on 2019-05-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/')),
                ('titulo', models.CharField(max_length=120, null=True)),
                ('resumen', models.TextField(null=True)),
                ('texto_descripcion', models.TextField(null=True)),
                ('fecha_del_evento', models.DateTimeField()),
                ('fecha_de_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
