# Generated by Django 2.2.1 on 2019-05-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_auto_20190505_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha_de_publicacion',
            field=models.DateTimeField(),
        ),
    ]
