# Generated by Django 2.2.1 on 2019-05-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_auto_20190505_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='tipo',
            field=models.CharField(default='noticias', max_length=10),
        ),
    ]
